# Generated by Django 2.1.7 on 2019-03-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190315_1757'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='journal',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Subscriber'),
            preserve_default=False,
        ),
    ]
