# Generated by Django 2.1.7 on 2019-03-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190227_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='verif_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
