# Generated by Django 2.1.7 on 2019-03-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190314_0204'),
        ('users', '0005_auto_20190315_1757'),
    ]

    operations = [
    ]
